# Generated by Django 2.1.3 on 2018-11-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('writer', models.CharField(max_length=250)),
                ('year', models.CharField(max_length=250)),
                ('month', models.CharField(max_length=250)),
                ('day', models.CharField(max_length=250)),
            ],
        ),
    ]
