# Generated by Django 2.1.3 on 2018-11-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='writer',
        ),
        migrations.AddField(
            model_name='articles',
            name='writer',
            field=models.CharField(default=1234, max_length=250),
            preserve_default=False,
        ),
    ]
