# Generated by Django 2.1.3 on 2018-12-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20181127_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.CharField(max_length=250)),
                ('like', models.CharField(max_length=250)),
                ('point', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('commentor', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='articles',
            name='like',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articles',
            name='point',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
