# Generated by Django 2.1.3 on 2018-12-01 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20181201_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='point',
            new_name='points',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='point',
            new_name='points',
        ),
    ]
