# Generated by Django 2.1.3 on 2018-11-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='password',
            field=models.CharField(default=1234, max_length=250),
            preserve_default=False,
        ),
    ]
