# Generated by Django 2.1.3 on 2018-11-28 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20181127_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='username',
            new_name='user_name',
        ),
    ]
