# Generated by Django 2.1.3 on 2018-12-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_auto_20181201_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='money',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='points',
            field=models.FloatField(null=True),
        ),
    ]
