# Generated by Django 2.1.3 on 2018-12-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_auto_20181201_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='money',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='points',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
