# Generated by Django 2.1.3 on 2018-12-09 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_auto_20181202_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='age',
            field=models.IntegerField(blank=True, default=18, null=True),
        ),
    ]
